<h1>chocopy 외전1 - 저 처럼 numpy 배열의 axis=0,1,2가 헷갈리는 분들 위해<h1/>

In [2]:
import numpy as np

In [3]:
arr = np.arange(1, 13).reshape(2, 2, 3)
#행, 열, 깊이
#2,   2,   3
#0,   1,   2

In [20]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
np.array([[arr[0][0][0] + arr[0][0][1] + arr[0][0][2], arr[0][1][0] + arr[0][1][1] + arr[0][1][2]],
[arr[1][0][0] + arr[1][0][1] + arr[1][0][2], arr[1][1][0] + arr[1][1][1] + arr[1][1][2]]])

array([[ 6, 15],
       [24, 33]])

In [5]:
np.sum(arr)

78

In [6]:
np.sum(arr, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [7]:
np.sum(arr, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [8]:
np.sum(arr, axis=2)

array([[ 6, 15],
       [24, 33]])